- hosts: remote
  sudo: yes
  roles:
      - swap
      - docker
      - users
      - packages
      - python
      - newrelic
      - logviewer
      - supervisor
      - {role: security, open_ports: [80,22]}