- name: Upgrade ubuntu packages
  sudo: yes
  apt: upgrade=yes update_cache=yes

- name: Install ubuntu packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
      - unzip
      - supervisor

