- name: Install Python related ubuntu packages
  apt: pkg={{ item }} state=installed
  with_items:
      - python-setuptools
      - python-dev
      - python3-dev
      - python3-setuptools


- name: Check if pip is installed
  shell: 'pip3'
  register: result
  args:
    executable: /bin/bash
  changed_when: False
  ignore_errors: True

- name: Install pip
  shell: curl https://bootstrap.pypa.io/get-pip.py | python3
  args:
    executable: /bin/bash
  when: result|failed

- name: Install required python packages
  pip: name={{item}} state=present executable=pip3
  with_items:
    - docker-py
    - nose
    - flask
    - gunicorn