- name: Enable ports for forwading.
  ufw: rule=allow port={{item}}
  with_items: open_ports

- name: Enable the firewall.
  ufw: state=enabled policy=deny

- name: Install fail2ban
  apt: pkg=fail2ban

- name: Copy fail2ban config files.
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - {src: 'jail.local', dest: '/etc/fail2ban/jail.local' }
    - {src: 'ufw-ssh.conf', dest: '/etc/fail2ban/action.d/ufw-ssh.conf'}

- name: Reload fail2ban
  service: name=fail2ban state=restarted