- name: Add the docker key
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add the docker repository
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main'

- name: install docker
  apt: name=lxc-docker